language: python

python:
  - "3.5"
  - "3.6"

sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq qttools5-dev-tools
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - pip install -r requirements.txt

before_script:
  - cd example

script:
  - python example_pyqt5.py --travis
